In [1]:
import sys
# sys.path.append('/path/to/mlpractical')
from mlp.test_methods import test_dropout_layer
import numpy as np

fprop_test, fprop_output, fprop_correct, \
bprop_test, bprop_output, bprop_correct = test_dropout_layer()

# assert fprop_test == 1.0, (
# 'The dropout layer fprop functionality test failed'
# 'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
# .format(fprop_correct, fprop_output, fprop_output-fprop_correct)
# )

print("Dropout Layer Fprop Functionality Test Passed")

assert bprop_test == 1.0, (
'The dropout layer bprop functionality test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(bprop_correct, bprop_output, bprop_output-bprop_correct)
)

print("Dropout Layer Bprop Test Passed")

helloooooooooooooooooooooooooooo
Fprop mask:
 [[[[1. 1. 0. ... 1. 0. 1.]
   [1. 1. 0. ... 1. 1. 1.]
   [1. 0. 0. ... 0. 0. 0.]
   ...
   [0. 1. 1. ... 0. 1. 1.]
   [0. 0. 0. ... 1. 0. 1.]
   [0. 0. 0. ... 1. 0. 1.]]

  [[0. 0. 1. ... 0. 0. 0.]
   [0. 1. 1. ... 0. 1. 0.]
   [1. 1. 0. ... 1. 0. 0.]
   ...
   [0. 0. 1. ... 0. 1. 0.]
   [0. 0. 0. ... 0. 1. 0.]
   [1. 1. 0. ... 1. 1. 1.]]

  [[0. 0. 1. ... 0. 0. 1.]
   [0. 1. 0. ... 0. 1. 0.]
   [1. 0. 0. ... 1. 0. 0.]
   ...
   [1. 1. 1. ... 0. 0. 1.]
   [0. 1. 1. ... 1. 0. 0.]
   [0. 1. 1. ... 0. 0. 0.]]]


 [[[1. 1. 0. ... 1. 0. 1.]
   [1. 1. 0. ... 1. 1. 1.]
   [1. 0. 0. ... 0. 0. 0.]
   ...
   [0. 1. 1. ... 0. 1. 1.]
   [0. 0. 0. ... 1. 0. 1.]
   [0. 0. 0. ... 1. 0. 1.]]

  [[0. 0. 1. ... 0. 0. 0.]
   [0. 1. 1. ... 0. 1. 0.]
   [1. 1. 0. ... 1. 0. 0.]
   ...
   [0. 0. 1. ... 0. 1. 0.]
   [0. 0. 0. ... 0. 1. 0.]
   [1. 1. 0. ... 1. 1. 1.]]

  [[0. 0. 1. ... 0. 0. 1.]
   [0. 1. 0. ... 0. 1. 0.]
   [1. 0. 0. ... 1. 0. 0.]
   ...
   [1. 1.

AssertionError: The dropout layer bprop functionality test failedCorrect output is 

[[[[0. 0. 1. ... 0. 1. 0.]
   [0. 0. 1. ... 0. 0. 0.]
   [0. 1. 1. ... 1. 1. 1.]
   ...
   [1. 0. 0. ... 1. 0. 0.]
   [1. 1. 1. ... 0. 1. 0.]
   [1. 1. 1. ... 0. 1. 0.]]

  [[1. 1. 0. ... 1. 1. 1.]
   [1. 0. 0. ... 1. 0. 1.]
   [0. 0. 1. ... 0. 1. 1.]
   ...
   [1. 1. 0. ... 1. 0. 1.]
   [1. 1. 1. ... 1. 0. 1.]
   [0. 0. 1. ... 0. 0. 0.]]

  [[1. 1. 0. ... 1. 1. 0.]
   [1. 0. 1. ... 1. 0. 1.]
   [0. 1. 1. ... 0. 1. 1.]
   ...
   [0. 0. 0. ... 1. 1. 0.]
   [1. 0. 0. ... 0. 1. 1.]
   [1. 0. 0. ... 1. 1. 1.]]]


 [[[0. 0. 1. ... 0. 1. 0.]
   [0. 0. 1. ... 0. 0. 0.]
   [0. 1. 1. ... 1. 1. 1.]
   ...
   [1. 0. 0. ... 1. 0. 0.]
   [1. 1. 1. ... 0. 1. 0.]
   [1. 1. 1. ... 0. 1. 0.]]

  [[1. 1. 0. ... 1. 1. 1.]
   [1. 0. 0. ... 1. 0. 1.]
   [0. 0. 1. ... 0. 1. 1.]
   ...
   [1. 1. 0. ... 1. 0. 1.]
   [1. 1. 1. ... 1. 0. 1.]
   [0. 0. 1. ... 0. 0. 0.]]

  [[1. 1. 0. ... 1. 1. 0.]
   [1. 0. 1. ... 1. 0. 1.]
   [0. 1. 1. ... 0. 1. 1.]
   ...
   [0. 0. 0. ... 1. 1. 0.]
   [1. 0. 0. ... 0. 1. 1.]
   [1. 0. 0. ... 1. 1. 1.]]]


 [[[0. 0. 1. ... 0. 1. 0.]
   [0. 0. 1. ... 0. 0. 0.]
   [0. 1. 1. ... 1. 1. 1.]
   ...
   [1. 0. 0. ... 1. 0. 0.]
   [1. 1. 1. ... 0. 1. 0.]
   [1. 1. 1. ... 0. 1. 0.]]

  [[1. 1. 0. ... 1. 1. 1.]
   [1. 0. 0. ... 1. 0. 1.]
   [0. 0. 1. ... 0. 1. 1.]
   ...
   [1. 1. 0. ... 1. 0. 1.]
   [1. 1. 1. ... 1. 0. 1.]
   [0. 0. 1. ... 0. 0. 0.]]

  [[1. 1. 0. ... 1. 1. 0.]
   [1. 0. 1. ... 1. 0. 1.]
   [0. 1. 1. ... 0. 1. 1.]
   ...
   [0. 0. 0. ... 1. 1. 0.]
   [1. 0. 0. ... 0. 1. 1.]
   [1. 0. 0. ... 1. 1. 1.]]]


 ...


 [[[0. 0. 1. ... 0. 1. 0.]
   [0. 0. 1. ... 0. 0. 0.]
   [0. 1. 1. ... 1. 1. 1.]
   ...
   [1. 0. 0. ... 1. 0. 0.]
   [1. 1. 1. ... 0. 1. 0.]
   [1. 1. 1. ... 0. 1. 0.]]

  [[1. 1. 0. ... 1. 1. 1.]
   [1. 0. 0. ... 1. 0. 1.]
   [0. 0. 1. ... 0. 1. 1.]
   ...
   [1. 1. 0. ... 1. 0. 1.]
   [1. 1. 1. ... 1. 0. 1.]
   [0. 0. 1. ... 0. 0. 0.]]

  [[1. 1. 0. ... 1. 1. 0.]
   [1. 0. 1. ... 1. 0. 1.]
   [0. 1. 1. ... 0. 1. 1.]
   ...
   [0. 0. 0. ... 1. 1. 0.]
   [1. 0. 0. ... 0. 1. 1.]
   [1. 0. 0. ... 1. 1. 1.]]]


 [[[0. 0. 1. ... 0. 1. 0.]
   [0. 0. 1. ... 0. 0. 0.]
   [0. 1. 1. ... 1. 1. 1.]
   ...
   [1. 0. 0. ... 1. 0. 0.]
   [1. 1. 1. ... 0. 1. 0.]
   [1. 1. 1. ... 0. 1. 0.]]

  [[1. 1. 0. ... 1. 1. 1.]
   [1. 0. 0. ... 1. 0. 1.]
   [0. 0. 1. ... 0. 1. 1.]
   ...
   [1. 1. 0. ... 1. 0. 1.]
   [1. 1. 1. ... 1. 0. 1.]
   [0. 0. 1. ... 0. 0. 0.]]

  [[1. 1. 0. ... 1. 1. 0.]
   [1. 0. 1. ... 1. 0. 1.]
   [0. 1. 1. ... 0. 1. 1.]
   ...
   [0. 0. 0. ... 1. 1. 0.]
   [1. 0. 0. ... 0. 1. 1.]
   [1. 0. 0. ... 1. 1. 1.]]]


 [[[0. 0. 1. ... 0. 1. 0.]
   [0. 0. 1. ... 0. 0. 0.]
   [0. 1. 1. ... 1. 1. 1.]
   ...
   [1. 0. 0. ... 1. 0. 0.]
   [1. 1. 1. ... 0. 1. 0.]
   [1. 1. 1. ... 0. 1. 0.]]

  [[1. 1. 0. ... 1. 1. 1.]
   [1. 0. 0. ... 1. 0. 1.]
   [0. 0. 1. ... 0. 1. 1.]
   ...
   [1. 1. 0. ... 1. 0. 1.]
   [1. 1. 1. ... 1. 0. 1.]
   [0. 0. 1. ... 0. 0. 0.]]

  [[1. 1. 0. ... 1. 1. 0.]
   [1. 0. 1. ... 1. 0. 1.]
   [0. 1. 1. ... 0. 1. 1.]
   ...
   [0. 0. 0. ... 1. 1. 0.]
   [1. 0. 0. ... 0. 1. 1.]
   [1. 0. 0. ... 1. 1. 1.]]]]

 but returned output is 

[[[[1. 1. 0. ... 1. 0. 1.]
   [1. 1. 0. ... 1. 1. 1.]
   [1. 0. 0. ... 0. 0. 0.]
   ...
   [0. 1. 1. ... 0. 1. 1.]
   [0. 0. 0. ... 1. 0. 1.]
   [0. 0. 0. ... 1. 0. 1.]]

  [[0. 0. 1. ... 0. 0. 0.]
   [0. 1. 1. ... 0. 1. 0.]
   [1. 1. 0. ... 1. 0. 0.]
   ...
   [0. 0. 1. ... 0. 1. 0.]
   [0. 0. 0. ... 0. 1. 0.]
   [1. 1. 0. ... 1. 1. 1.]]

  [[0. 0. 1. ... 0. 0. 1.]
   [0. 1. 0. ... 0. 1. 0.]
   [1. 0. 0. ... 1. 0. 0.]
   ...
   [1. 1. 1. ... 0. 0. 1.]
   [0. 1. 1. ... 1. 0. 0.]
   [0. 1. 1. ... 0. 0. 0.]]]


 [[[1. 1. 0. ... 1. 0. 1.]
   [1. 1. 0. ... 1. 1. 1.]
   [1. 0. 0. ... 0. 0. 0.]
   ...
   [0. 1. 1. ... 0. 1. 1.]
   [0. 0. 0. ... 1. 0. 1.]
   [0. 0. 0. ... 1. 0. 1.]]

  [[0. 0. 1. ... 0. 0. 0.]
   [0. 1. 1. ... 0. 1. 0.]
   [1. 1. 0. ... 1. 0. 0.]
   ...
   [0. 0. 1. ... 0. 1. 0.]
   [0. 0. 0. ... 0. 1. 0.]
   [1. 1. 0. ... 1. 1. 1.]]

  [[0. 0. 1. ... 0. 0. 1.]
   [0. 1. 0. ... 0. 1. 0.]
   [1. 0. 0. ... 1. 0. 0.]
   ...
   [1. 1. 1. ... 0. 0. 1.]
   [0. 1. 1. ... 1. 0. 0.]
   [0. 1. 1. ... 0. 0. 0.]]]


 [[[1. 1. 0. ... 1. 0. 1.]
   [1. 1. 0. ... 1. 1. 1.]
   [1. 0. 0. ... 0. 0. 0.]
   ...
   [0. 1. 1. ... 0. 1. 1.]
   [0. 0. 0. ... 1. 0. 1.]
   [0. 0. 0. ... 1. 0. 1.]]

  [[0. 0. 1. ... 0. 0. 0.]
   [0. 1. 1. ... 0. 1. 0.]
   [1. 1. 0. ... 1. 0. 0.]
   ...
   [0. 0. 1. ... 0. 1. 0.]
   [0. 0. 0. ... 0. 1. 0.]
   [1. 1. 0. ... 1. 1. 1.]]

  [[0. 0. 1. ... 0. 0. 1.]
   [0. 1. 0. ... 0. 1. 0.]
   [1. 0. 0. ... 1. 0. 0.]
   ...
   [1. 1. 1. ... 0. 0. 1.]
   [0. 1. 1. ... 1. 0. 0.]
   [0. 1. 1. ... 0. 0. 0.]]]


 ...


 [[[1. 1. 0. ... 1. 0. 1.]
   [1. 1. 0. ... 1. 1. 1.]
   [1. 0. 0. ... 0. 0. 0.]
   ...
   [0. 1. 1. ... 0. 1. 1.]
   [0. 0. 0. ... 1. 0. 1.]
   [0. 0. 0. ... 1. 0. 1.]]

  [[0. 0. 1. ... 0. 0. 0.]
   [0. 1. 1. ... 0. 1. 0.]
   [1. 1. 0. ... 1. 0. 0.]
   ...
   [0. 0. 1. ... 0. 1. 0.]
   [0. 0. 0. ... 0. 1. 0.]
   [1. 1. 0. ... 1. 1. 1.]]

  [[0. 0. 1. ... 0. 0. 1.]
   [0. 1. 0. ... 0. 1. 0.]
   [1. 0. 0. ... 1. 0. 0.]
   ...
   [1. 1. 1. ... 0. 0. 1.]
   [0. 1. 1. ... 1. 0. 0.]
   [0. 1. 1. ... 0. 0. 0.]]]


 [[[1. 1. 0. ... 1. 0. 1.]
   [1. 1. 0. ... 1. 1. 1.]
   [1. 0. 0. ... 0. 0. 0.]
   ...
   [0. 1. 1. ... 0. 1. 1.]
   [0. 0. 0. ... 1. 0. 1.]
   [0. 0. 0. ... 1. 0. 1.]]

  [[0. 0. 1. ... 0. 0. 0.]
   [0. 1. 1. ... 0. 1. 0.]
   [1. 1. 0. ... 1. 0. 0.]
   ...
   [0. 0. 1. ... 0. 1. 0.]
   [0. 0. 0. ... 0. 1. 0.]
   [1. 1. 0. ... 1. 1. 1.]]

  [[0. 0. 1. ... 0. 0. 1.]
   [0. 1. 0. ... 0. 1. 0.]
   [1. 0. 0. ... 1. 0. 0.]
   ...
   [1. 1. 1. ... 0. 0. 1.]
   [0. 1. 1. ... 1. 0. 0.]
   [0. 1. 1. ... 0. 0. 0.]]]


 [[[1. 1. 0. ... 1. 0. 1.]
   [1. 1. 0. ... 1. 1. 1.]
   [1. 0. 0. ... 0. 0. 0.]
   ...
   [0. 1. 1. ... 0. 1. 1.]
   [0. 0. 0. ... 1. 0. 1.]
   [0. 0. 0. ... 1. 0. 1.]]

  [[0. 0. 1. ... 0. 0. 0.]
   [0. 1. 1. ... 0. 1. 0.]
   [1. 1. 0. ... 1. 0. 0.]
   ...
   [0. 0. 1. ... 0. 1. 0.]
   [0. 0. 0. ... 0. 1. 0.]
   [1. 1. 0. ... 1. 1. 1.]]

  [[0. 0. 1. ... 0. 0. 1.]
   [0. 1. 0. ... 0. 1. 0.]
   [1. 0. 0. ... 1. 0. 0.]
   ...
   [1. 1. 1. ... 0. 0. 1.]
   [0. 1. 1. ... 1. 0. 0.]
   [0. 1. 1. ... 0. 0. 0.]]]]

 difference is 

[[[[ 1.  1. -1. ...  1. -1.  1.]
   [ 1.  1. -1. ...  1.  1.  1.]
   [ 1. -1. -1. ... -1. -1. -1.]
   ...
   [-1.  1.  1. ... -1.  1.  1.]
   [-1. -1. -1. ...  1. -1.  1.]
   [-1. -1. -1. ...  1. -1.  1.]]

  [[-1. -1.  1. ... -1. -1. -1.]
   [-1.  1.  1. ... -1.  1. -1.]
   [ 1.  1. -1. ...  1. -1. -1.]
   ...
   [-1. -1.  1. ... -1.  1. -1.]
   [-1. -1. -1. ... -1.  1. -1.]
   [ 1.  1. -1. ...  1.  1.  1.]]

  [[-1. -1.  1. ... -1. -1.  1.]
   [-1.  1. -1. ... -1.  1. -1.]
   [ 1. -1. -1. ...  1. -1. -1.]
   ...
   [ 1.  1.  1. ... -1. -1.  1.]
   [-1.  1.  1. ...  1. -1. -1.]
   [-1.  1.  1. ... -1. -1. -1.]]]


 [[[ 1.  1. -1. ...  1. -1.  1.]
   [ 1.  1. -1. ...  1.  1.  1.]
   [ 1. -1. -1. ... -1. -1. -1.]
   ...
   [-1.  1.  1. ... -1.  1.  1.]
   [-1. -1. -1. ...  1. -1.  1.]
   [-1. -1. -1. ...  1. -1.  1.]]

  [[-1. -1.  1. ... -1. -1. -1.]
   [-1.  1.  1. ... -1.  1. -1.]
   [ 1.  1. -1. ...  1. -1. -1.]
   ...
   [-1. -1.  1. ... -1.  1. -1.]
   [-1. -1. -1. ... -1.  1. -1.]
   [ 1.  1. -1. ...  1.  1.  1.]]

  [[-1. -1.  1. ... -1. -1.  1.]
   [-1.  1. -1. ... -1.  1. -1.]
   [ 1. -1. -1. ...  1. -1. -1.]
   ...
   [ 1.  1.  1. ... -1. -1.  1.]
   [-1.  1.  1. ...  1. -1. -1.]
   [-1.  1.  1. ... -1. -1. -1.]]]


 [[[ 1.  1. -1. ...  1. -1.  1.]
   [ 1.  1. -1. ...  1.  1.  1.]
   [ 1. -1. -1. ... -1. -1. -1.]
   ...
   [-1.  1.  1. ... -1.  1.  1.]
   [-1. -1. -1. ...  1. -1.  1.]
   [-1. -1. -1. ...  1. -1.  1.]]

  [[-1. -1.  1. ... -1. -1. -1.]
   [-1.  1.  1. ... -1.  1. -1.]
   [ 1.  1. -1. ...  1. -1. -1.]
   ...
   [-1. -1.  1. ... -1.  1. -1.]
   [-1. -1. -1. ... -1.  1. -1.]
   [ 1.  1. -1. ...  1.  1.  1.]]

  [[-1. -1.  1. ... -1. -1.  1.]
   [-1.  1. -1. ... -1.  1. -1.]
   [ 1. -1. -1. ...  1. -1. -1.]
   ...
   [ 1.  1.  1. ... -1. -1.  1.]
   [-1.  1.  1. ...  1. -1. -1.]
   [-1.  1.  1. ... -1. -1. -1.]]]


 ...


 [[[ 1.  1. -1. ...  1. -1.  1.]
   [ 1.  1. -1. ...  1.  1.  1.]
   [ 1. -1. -1. ... -1. -1. -1.]
   ...
   [-1.  1.  1. ... -1.  1.  1.]
   [-1. -1. -1. ...  1. -1.  1.]
   [-1. -1. -1. ...  1. -1.  1.]]

  [[-1. -1.  1. ... -1. -1. -1.]
   [-1.  1.  1. ... -1.  1. -1.]
   [ 1.  1. -1. ...  1. -1. -1.]
   ...
   [-1. -1.  1. ... -1.  1. -1.]
   [-1. -1. -1. ... -1.  1. -1.]
   [ 1.  1. -1. ...  1.  1.  1.]]

  [[-1. -1.  1. ... -1. -1.  1.]
   [-1.  1. -1. ... -1.  1. -1.]
   [ 1. -1. -1. ...  1. -1. -1.]
   ...
   [ 1.  1.  1. ... -1. -1.  1.]
   [-1.  1.  1. ...  1. -1. -1.]
   [-1.  1.  1. ... -1. -1. -1.]]]


 [[[ 1.  1. -1. ...  1. -1.  1.]
   [ 1.  1. -1. ...  1.  1.  1.]
   [ 1. -1. -1. ... -1. -1. -1.]
   ...
   [-1.  1.  1. ... -1.  1.  1.]
   [-1. -1. -1. ...  1. -1.  1.]
   [-1. -1. -1. ...  1. -1.  1.]]

  [[-1. -1.  1. ... -1. -1. -1.]
   [-1.  1.  1. ... -1.  1. -1.]
   [ 1.  1. -1. ...  1. -1. -1.]
   ...
   [-1. -1.  1. ... -1.  1. -1.]
   [-1. -1. -1. ... -1.  1. -1.]
   [ 1.  1. -1. ...  1.  1.  1.]]

  [[-1. -1.  1. ... -1. -1.  1.]
   [-1.  1. -1. ... -1.  1. -1.]
   [ 1. -1. -1. ...  1. -1. -1.]
   ...
   [ 1.  1.  1. ... -1. -1.  1.]
   [-1.  1.  1. ...  1. -1. -1.]
   [-1.  1.  1. ... -1. -1. -1.]]]


 [[[ 1.  1. -1. ...  1. -1.  1.]
   [ 1.  1. -1. ...  1.  1.  1.]
   [ 1. -1. -1. ... -1. -1. -1.]
   ...
   [-1.  1.  1. ... -1.  1.  1.]
   [-1. -1. -1. ...  1. -1.  1.]
   [-1. -1. -1. ...  1. -1.  1.]]

  [[-1. -1.  1. ... -1. -1. -1.]
   [-1.  1.  1. ... -1.  1. -1.]
   [ 1.  1. -1. ...  1. -1. -1.]
   ...
   [-1. -1.  1. ... -1.  1. -1.]
   [-1. -1. -1. ... -1.  1. -1.]
   [ 1.  1. -1. ...  1.  1.  1.]]

  [[-1. -1.  1. ... -1. -1.  1.]
   [-1.  1. -1. ... -1.  1. -1.]
   [ 1. -1. -1. ...  1. -1. -1.]
   ...
   [ 1.  1.  1. ... -1. -1.  1.]
   [-1.  1.  1. ...  1. -1. -1.]
   [-1.  1.  1. ... -1. -1. -1.]]]]

In [ ]:
from mlp.test_methods import test_L1_Penalty


call_test, call_output, call_correct, \
grad_test, grad_output, grad_correct = test_L1_Penalty()


assert call_test == 1.0, (
'The call function for L1 Penalty test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(call_correct, call_output, call_output-call_correct)
)

print("L1 Penalty Call Functionality Test Passed")

assert grad_test == 1.0, (
'The grad function for L1 Penalty test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(grad_correct, grad_output, grad_output-grad_correct, grad_output/grad_correct)
)



print("L1 Penalty Grad Function Test Passed")

In [ ]:
from mlp.test_methods import test_L2_Penalty


call_test, call_output, call_correct, \
grad_test, grad_output, grad_correct = test_L2_Penalty()


assert call_test == 1.0, (
'The call function for L2 Penalty test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(call_correct, call_output, call_output-call_correct)
)

print("L2 Penalty Call Functionality Test Passed")

assert grad_test == 1.0, (
'The grad function for L2 Penalty test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(grad_correct, grad_output, grad_output-grad_correct, grad_output/grad_correct)
)



print("L2 Penalty Grad Function Test Passed")